del ".\GameData\Teams\Zonda_ R_GT\Team 1\00001_ZondaGT.car"
del ".\GameData\Teams\Zonda_ R_GT\Team 1\00003_ZondaGT.car"
del ".\GameData\Teams\GT_Club\AstonMartin_DBRS9\Charden Racing\00008_Charden_Racing.car"
del ".\GameData\Teams\GT_Club\AstonMartin_DBRS9\Forsberg Motorsport\00005_Forsberg_Motorsport.car"
del ".\GameData\Teams\GT_Club\AstonMartin_DBRS9\Scott Racing Team\00026_Scott_Racing.car"
del ".\GameData\Teams\GT_Club\AstonMartin_DBRS9\Scuderia SportAutoMoto\00001_Scuderia_SportAuto.car"
del ".\GameData\Teams\GT_Club\AstonMartin_DBRS9\Team Swiss Spirit\00017_Swiss_Spirit.car"
del ".\GameData\Teams\GT_Club\BMW_Z4\Autosport Racing\00007_Autosport_Racing.car"
del ".\GameData\Teams\GT_Club\BMW_Z4\BMW Motorsport\00004_BMW_Motorsport.car"
del ".\GameData\Teams\GT_Club\BMW_Z4\Dell Racing Team\00054_Dell_Racing.car"
del ".\GameData\Teams\GT_Club\BMW_Z4\Ecurie Hugenholtz\00027_Ecurie_Hugenholtz.car"
del ".\GameData\Teams\GT_Club\BMW_Z4\KW Competition\00011_KW_Competition.car"
del ".\GameData\Teams\GT_Club\BMW_Z4\Team Essex\00003_Team_Essex.car"
del ".\GameData\Teams\GT_Club\SEAT_CUPRA_GT\Forsberg Motorsport\00023_Forsberg_Motorsport.car"
del ".\GameData\Teams\GT_Club\SEAT_CUPRA_GT\Logitech Competition\00022_Logitech_Comp.car"
del ".\GameData\Teams\GT_Club\SEAT_CUPRA_GT\Pyxidium Competition\00019_Pyxidum_Comp.car"
del ".\GameData\Teams\GT_Club\SEAT_CUPRA_GT\Team CannonBall8000\00018_CanonBall8000.car"
del ".\GameData\Teams\GT_Club\SEAT_CUPRA_GT\TS Motorsport\00021_TS_Motorsport.car"
del ".\GameData\Teams\GT_Club\Vertigo_Streiff\Ecurie Auto Hebdo\00015_Ecurie_Auto_Hebdo.car"
del ".\GameData\Teams\GT_Club\Vertigo_Streiff\Ecurie Gillet\00101_Ecurie_Gillet.car"
del ".\GameData\Teams\GT_Club\Vertigo_Streiff\Hype Racing Team\00006_Hype_Racing.car"
del ".\GameData\Teams\GT_Club\Vertigo_Streiff\RaceRoom Motorsport\00012_RaceRoom.car"
del ".\GameData\Teams\GT_Club\Vertigo_Streiff\SimBin Racing\00020_SimBin_Racing.car"
del ".\GameData\Teams\GT_Club\VIPER_CC\Logitech Competition\00009_Logitech_Comp.car"
del ".\GameData\Teams\GT_Club\VIPER_CC\Raadzaak Racing\00014_Raadzaaak_Racing.car"
del ".\GameData\Teams\GT_Club\VIPER_CC\Scuderia Evo\00002_Scuderia_Evo.car"
del ".\GameData\Teams\GT_Club\VIPER_CC\SimBin Racing\00010_SimBin_Racing.car"
del ".\GameData\Teams\GT_Club\VIPER_CC\Team Boutsen Aviation\00016_Boutsen_Aviation.car"
del ".\GameData\Teams\GT_Pro\AstonMartin_DB9R\Aston Martin Racing\00007_Team_Aston_Martin_1.car"
del ".\GameData\Teams\GT_Pro\AstonMartin_DB9R\Autosport Racing\00014_Team_Aston_Martin_1.car"
del ".\GameData\Teams\GT_Pro\AstonMartin_DB9R\BenQ Racing Team\00027_Team_Aston_Martin_1.car"
del ".\GameData\Teams\GT_Pro\AstonMartin_DB9R\Gigawave Motorsport\00016_Team_Aston_Martin_1.car"
del ".\GameData\Teams\GT_Pro\AstonMartin_DB9R\Just Marketing Racing\00034_Team_Aston_Martin_1.car"
del ".\GameData\Teams\GT_Pro\AstonMartin_DB9R\KW Competition\00009_Team_Aston_Martin_1.car"
del ".\GameData\Teams\GT_Pro\AstonMartin_DB9R\Raadzaak Racing\00011_Team_Aston_Martin_1.car"
del ".\GameData\Teams\GT_Pro\AstonMartin_DB9R\Team CannonBall8000\00018_Team_Aston_Martin_1.car"
del ".\GameData\Teams\GT_Pro\Audi_R8GT\Conrad Racing Team\00044_Conrad_Racing.car"
del ".\GameData\Teams\GT_Pro\Audi_R8GT\Logitech Competition\00023_Logitech_Competition.car"
del ".\GameData\Teams\GT_Pro\Audi_R8GT\Puma Racing Team\00024_Puma_Racing.car"
del ".\GameData\Teams\GT_Pro\Audi_R8GT\Scuderia Bio-Fox\00036_Scuderia_Bio-Fox.car"
del ".\GameData\Teams\GT_Pro\Audi_R8GT\Scuderia Evo\00033_Scuderia_Evo.car"
del ".\GameData\Teams\GT_Pro\Audi_R8GT\TVK Project Racing\00021_TVK_Project.car"
del ".\GameData\Teams\GT_Pro\Corvette_C5R\Autosport Racing\00006_Autosport_Racing.car"
del ".\GameData\Teams\GT_Pro\Corvette_C5R\Incide Motorsport\00004_Incide_Motorsport.car"
del ".\GameData\Teams\GT_Pro\Corvette_C5R\Puma Racing Team\00015_Puma_Racing.car"
del ".\GameData\Teams\GT_Pro\Corvette_C5R\Scuderia TripleHead2Go\00038_TripleHead2Go.car"
del ".\GameData\Teams\GT_Pro\Corvette_C5R\Team Lizard\00007_Team_Lizard.car"
del ".\GameData\Teams\GT_Pro\Corvette_C6R\BenQ Racing Team\00020_BenQ_Racing.car"
del ".\GameData\Teams\GT_Pro\Corvette_C6R\Crash or Byrne Racing\00030_Crash_and_Byrne.car"
del ".\GameData\Teams\GT_Pro\Corvette_C6R\Gigawave Motorsport\00001_Gigawave_Motorsport.car"
del ".\GameData\Teams\GT_Pro\Corvette_C6R\KW Competition\00008_KW_Competition.car"
del ".\GameData\Teams\GT_Pro\Corvette_C6R\Team CannonBall8000\00012_CanonBall8000.car"
del ".\GameData\Teams\GT_Pro\Gumpert_Apollo\Ecurie Auto Hebdo\00046_Ecurie_Auto_Hebdo.car"
del ".\GameData\Teams\GT_Pro\Gumpert_Apollo\Motortorget Racing\00042_Motortorget_Racing.car"
del ".\GameData\Teams\GT_Pro\Gumpert_Apollo\Scuderia SportAutoMoto\00050_Scuderia_Sport.car"
del ".\GameData\Teams\GT_Pro\Gumpert_Apollo\Team Gumpert\00048_Team_Gumpert.car"
del ".\GameData\Teams\GT_Pro\Gumpert_Apollo\Team Navicam\00045_Team_Navicam.car"
del ".\GameData\Teams\GT_Pro\Koenigsegg_CCGT\Danielsson Motorsport\00025_Danielsson_Motorsport.car"
del ".\GameData\Teams\GT_Pro\Koenigsegg_CCGT\Koenigsegg Competition\00047_Koenigsegg_Comp.car"
del ".\GameData\Teams\GT_Pro\Koenigsegg_CCGT\Raadzaak Racing\00010_Raadzaak_Racing.car"
del ".\GameData\Teams\GT_Pro\Koenigsegg_CCGT\Team Navicam\00041_Team_Navicam.car"
del ".\GameData\Teams\GT_Pro\Koenigsegg_CCGT\Team Red Devil\00040_Red_Devil.car"
del ".\GameData\Teams\GT_Pro\Lister_Storm\BenQ Racing Team\00043_BenQ_Racing.car"
del ".\GameData\Teams\GT_Pro\Lister_Storm\Cavendish Finance Racing\00035_Cavendish.car"
del ".\GameData\Teams\GT_Pro\Lister_Storm\Lister Storm Racing\00049_Lister_Storm.car"
del ".\GameData\Teams\GT_Pro\Lister_Storm\LSD Racing\00022_LSD_Racing.car"
del ".\GameData\Teams\GT_Pro\Lister_Storm\Motors TV Competition\00037_Motors_TV.car"
del ".\GameData\Teams\GT_Pro\Saleen_S7R\Autosport Racing\00019_Autosport_Racing.car"
del ".\GameData\Teams\GT_Pro\Saleen_S7R\Belltech Racing\00003_Beltech_Racing.car"
del ".\GameData\Teams\GT_Pro\Saleen_S7R\Crash or Byrne Racing\00031_Crash_Byrne.car"
del ".\GameData\Teams\GT_Pro\Saleen_S7R\Ecurie Auto Hebdo\00005_Ecurie_Auto_Hebo.car"
del ".\GameData\Teams\GT_Pro\Saleen_S7R\RaceRoom Motorsport\00028_RaceRoom.car"
del ".\GameData\Teams\GT_Pro\Viper_GTSR\Bilsport Racing Team\00039_Bilsport_Racing.car"
del ".\GameData\Teams\GT_Pro\Viper_GTSR\Derek Warwick Motorsport\00029_Derek_Warwick.car"
del ".\GameData\Teams\GT_Pro\Viper_GTSR\Henrik Roos Motorsport\00002_Henrik_Roos.car"
del ".\GameData\Teams\GT_Pro\Viper_GTSR\RaceRoom Motorsport\00032_RaceRoom_Motorsport.car"
del ".\GameData\Teams\GT_Pro\Viper_GTSR\Team Navicam\00017_Navicam.car"
del ".\GameData\Teams\GT_Sport\Bmw_M3_GTR\Bilsport Racing Team\00021_Bilsport_Racing.car"
del ".\GameData\Teams\GT_Sport\Bmw_M3_GTR\Camforce Racing\00003_Evo_Racing.car"
del ".\GameData\Teams\GT_Sport\Bmw_M3_GTR\Dell Racing Team\00028_Dell_Racing.car"
del ".\GameData\Teams\GT_Sport\Bmw_M3_GTR\Puma Racing Team\00002_Puma_Racing.car"
del ".\GameData\Teams\GT_Sport\Bmw_M3_GTR\SimBin Racing\00014_SimBin_Racing.car"
del ".\GameData\Teams\GT_Sport\Bmw_M3_GTR\Team CannonBall8000\00033_CanonBall8000.car"
del ".\GameData\Teams\GT_Sport\Corvette_C6_GT2\Bilsport Racing Team\00026_Bilsport_Racing.car"
del ".\GameData\Teams\GT_Sport\Corvette_C6_GT2\Dynamic Motorsports\00022_Dynamic_Motorsports.car"
del ".\GameData\Teams\GT_Sport\Corvette_C6_GT2\Logitech Competition\00016_Logitech_Comp.car"
del ".\GameData\Teams\GT_Sport\Corvette_C6_GT2\RaceRoom Motorsport\00036_RaceRoom_Motorsport.car"
del ".\GameData\Teams\GT_Sport\Corvette_C6_GT2\Scuderia SportAutoMoto\00011_Scuderia_Sport.car"
del ".\GameData\Teams\GT_Sport\Marcos_Marcorelly\Hype Racing Team\00020_Hype_Racing.car"
del ".\GameData\Teams\GT_Sport\Marcos_Marcorelly\Marcos Racing\00012_Marcos_Racing.car"
del ".\GameData\Teams\GT_Sport\Marcos_Marcorelly\Scuderia Evo\00005_Scuderia_Evo.car"
del ".\GameData\Teams\GT_Sport\Marcos_Marcorelly\Team Lizard\00027_Team_Lizard.car"
del ".\GameData\Teams\GT_Sport\Marcos_Marcorelly\Team Racing for Holland\00032_Racing_Holland.car"
del ".\GameData\Teams\GT_Sport\Mosler\Autosport Racing\00007_Mosler_AR.car"
del ".\GameData\Teams\GT_Sport\Mosler\Dell Racing Team\00029_Dell_Racing.car"
del ".\GameData\Teams\GT_Sport\Mosler\Scuderia Evo\00018_Scuderia_Evo.car"
del ".\GameData\Teams\GT_Sport\Mosler\SimBin Racing\00017_Camforce_Racing.car"
del ".\GameData\Teams\GT_Sport\Mosler\SkyQuest Competition\00035_SkyQuest_Comp.car"
del ".\GameData\Teams\GT_Sport\Seat_Toledo\GTG Motorsport\00037_GTG_Motorsport.car"
del ".\GameData\Teams\GT_Sport\Seat_Toledo\Logitech Competition\00015_Logitech_Comp.car"
del ".\GameData\Teams\GT_Sport\Seat_Toledo\Scuderia Evo\00008_Scuderia_Evo.car"
del ".\GameData\Teams\GT_Sport\Seat_Toledo\Team City Self-Storage\00004_City-Self_Storage.car"
del ".\GameData\Teams\GT_Sport\Seat_Toledo\Team Lizard\00010_Team_Lizard.car"
del ".\GameData\Teams\GT_Sport\Spyker_C8\Autosport Racing\00024_Autosport_Racing.car"
del ".\GameData\Teams\GT_Sport\Spyker_C8\Gigawave Motorsport\00001_Spyker_GM.car"
del ".\GameData\Teams\GT_Sport\Spyker_C8\Motors TV Comp\00030_Motors_TV.car"
del ".\GameData\Teams\GT_Sport\Spyker_C8\Scuderia Evo\00006_Scuderia_Evo.car"
del ".\GameData\Teams\GT_Sport\Spyker_C8\Team CannonBall8000\00034_CanonBall8000.car"
del ".\GameData\Teams\GT_Sport\Sunred_SR21\Clear Initiatives Racing\00009_Clear_Initiatives.car"
del ".\GameData\Teams\GT_Sport\Sunred_SR21\Escuderia SunRed\00031_Escuderia_SunRed.car"
del ".\GameData\Teams\GT_Sport\Sunred_SR21\Hype Racing Team\00023_Hype_Racing.car"
del ".\GameData\Teams\GT_Sport\Sunred_SR21\Logitech Competition\00019_Logitech_Comp.car"
del ".\GameData\Teams\GT_Sport\Sunred_SR21\Motors TV Competition\00025_Motors_TV.car"

del ".\GameData\Teams\BMW_M3_GT2\Teams\00051_M3.car"
del ".\GameData\Teams\BMW_M3_GT2\Teams\00052_M3.car"
del ".\GameData\Teams\BMW_M3_GT2\Teams\00053_M3.car"
del ".\GameData\Teams\BMW_M3_GT2\Teams\00054_M3.car"
del ".\GameData\Teams\BMW_M3_GT2\Teams\00055_M3.car"
del ".\GameData\Teams\BMW_M3_GT2\Teams\00056_M3.car"
del ".\GameData\Teams\BMW_M3_GT2\Teams\00057_M3.car"
del ".\GameData\Teams\BMW_M3_GT2\Teams\00058_M3.car"
del ".\GameData\Teams\BMW_M3_GT2\Teams\00059_M3.car"
del ".\GameData\Teams\BMW_M3_GT2\Teams\00060_M3.car"
del ".\GameData\Teams\BMW_M3_GT2\Teams\00061_M3.car"
del ".\GameData\Teams\BMW_M3_GT2\Teams\00062_M3.car"

del ".\GameData\Teams\production_cars\Audi_R8\Audi R8\00020_Team_White.car"
del ".\GameData\Teams\production_cars\Audi_R8\Audi R8\00021_Team_Red.car"
del ".\GameData\Teams\production_cars\Audi_R8\Audi R8\00022_Team_DarkGrey.car"
del ".\GameData\Teams\production_cars\Audi_R8\Audi R8\00023_Team_Iceblue.car"
del ".\GameData\Teams\production_cars\Audi_R8\Audi R8\00024_Team_Silver.car"
del ".\GameData\Teams\production_cars\Gumpert_Apollo\Black\00001_Team_Black.car"
del ".\GameData\Teams\production_cars\Gumpert_Apollo\Blue\00002_Team_Blue.car"
del ".\GameData\Teams\production_cars\Gumpert_Apollo\Orange\00003_Team_Orange.car"
del ".\GameData\Teams\production_cars\Gumpert_Apollo\Red\00004_Team_Red.car"
del ".\GameData\Teams\production_cars\Gumpert_Apollo\White\00005_Team_White.car"
del ".\GameData\Teams\production_cars\koenigsegg_ccx\CCX Teams\00006_CCX_Team_1.car"
del ".\GameData\Teams\production_cars\koenigsegg_ccx\CCX Teams\00007_CCX_Team_2.car"
del ".\GameData\Teams\production_cars\koenigsegg_ccx\CCX Teams\00008_CCX_Team_3.car"
del ".\GameData\Teams\production_cars\koenigsegg_ccx\CCX Teams\00009_CCX_Team_4.car"
del ".\GameData\Teams\production_cars\koenigsegg_ccx\CCX Teams\00010_CCX_Team_5.car"
del ".\GameData\Teams\production_cars\Viper_SRT10\SRT10 Teams\00011_SRT10.car"
del ".\GameData\Teams\production_cars\Viper_SRT10\SRT10 Teams\00012_SRT10.car"
del ".\GameData\Teams\production_cars\Viper_SRT10\SRT10 Teams\00013_SRT10.car"
del ".\GameData\Teams\production_cars\Viper_SRT10\SRT10 Teams\00014_SRT10.car"
del ".\GameData\Teams\production_cars\Viper_SRT10\SRT10 Teams\00015_SRT10.car"

del ".\GameData\Teams\wtcc_extreme\Alfa Romeo 156 Extreme\NTechnology\00015_NTechnology_X.car"
del ".\GameData\Teams\wtcc_extreme\Alfa Romeo 156 Extreme\NTechnology\00016_NTechnology_X.car"
del ".\GameData\Teams\wtcc_extreme\BMW E90 Extreme\BMW Team Germany\00002_BMW_X_Team_Germany.car"
del ".\GameData\Teams\wtcc_extreme\BMW E90 Extreme\BMW Team Germany\00003_BMW_X_Team_Germany.car"
del ".\GameData\Teams\wtcc_extreme\BMW E90 Extreme\BMW Team Italy-Spain\00004_BMW_X_Team_I-SP.car"
del ".\GameData\Teams\wtcc_extreme\BMW E90 Extreme\BMW Team Italy-Spain\00005_BMW_X_Team_I-SP.car"
del ".\GameData\Teams\wtcc_extreme\BMW E90 Extreme\BMW Team UK\00001_BMW_X_Team_UK.car"
del ".\GameData\Teams\wtcc_extreme\Chevrolet Lacetti Extreme\Chevrolet\00006_Chevrolet_X.car"
del ".\GameData\Teams\wtcc_extreme\Chevrolet Lacetti Extreme\Chevrolet\00007_Chevrolet_X.car"
del ".\GameData\Teams\wtcc_extreme\Chevrolet Lacetti Extreme\Chevrolet\00008_Chevrolet_X.car"
del ".\GameData\Teams\wtcc_extreme\Seat Leon Extreme\SEAT\00009_SEAT_X.car"
del ".\GameData\Teams\wtcc_extreme\Seat Leon Extreme\SEAT\00011_SEAT_X.car"
del ".\GameData\Teams\wtcc_extreme\Seat Leon Extreme\SEAT\00012_SEAT_X.car"
del ".\GameData\Teams\wtcc_extreme\Seat Leon Extreme\SEAT\00018_SEAT_X.car"

