del ".\GameData\Teams\STCC\Alfa Romeo 156 STCC Teams\MAGP\00020_StccAlfa01.car"
del ".\GameData\Teams\STCC\Audi_A4\Cawalli\00017_Cawalli.car"
del ".\GameData\Teams\STCC\Audi_A4\KMS\00014_KMS.car"
del ".\GameData\Teams\STCC\Audi_A4\KMS\00015_KMS.car"
del ".\GameData\Teams\STCC\BMS\Team1\UNC.car"
del ".\GameData\Teams\STCC\BMW 320i STCC Teams\Brovallen Motorsport\00097_Brocallen.car"
del ".\GameData\Teams\STCC\BMW 320i STCC Teams\Huggare Racing\00096_Huggare_Racing.car"
del ".\GameData\Teams\STCC\BMW 320i STCC Teams\Team Caliber\00093_Team_Caliber.car"
del ".\GameData\Teams\STCC\BMW 320i STCC Teams\Team Nya Akeriet\00094_Team_Nya.car"
del ".\GameData\Teams\STCC\BMW 320i STCC Teams\Tysslinge Racing\00095_Tysslinge_Racing.car"
del ".\GameData\Teams\STCC\BMW 320si STCC Teams\Elgh Motorsport\00028_Elgh_Motorsport.car"
del ".\GameData\Teams\STCC\BMW 320si STCC Teams\Flash Engineering\00003_Flash_Engineering.car"
del ".\GameData\Teams\STCC\BMW 320si STCC Teams\Flash Engineering Seq\00005_Flash_Engineering.car"
del ".\GameData\Teams\STCC\BMW 320si STCC Teams\Westcoast Racing\00001_Westcoast_Racing.car"
del ".\GameData\Teams\STCC\BMW 320si STCC Teams\Westcoast Racing\00006_Flash_Engineering.car"
del ".\GameData\Teams\STCC\Chevrolet Lacetti STCC Teams\Chevrolet Motorsport Sweden\00022_Chevrolet_Motorsport.car"
del ".\GameData\Teams\STCC\Honda Accord STCC Teams\Honda Racing\00004_Honda_Racing.car"
del ".\GameData\Teams\STCC\Honda Accord STCC Teams\Honda Racing\00007_Honda_Racing.car"
del ".\GameData\Teams\STCC\Peugeot_308\IPS Motorsport\21.car"
del ".\GameData\Teams\STCC\Seat Leon STCC Teams\Nordic Fine Art AB\00008_Nordic_Fine_Art.car"
del ".\GameData\Teams\STCC\Volvo_C30\Volvo Olsberg\00009_Volvo_Olsbergs.car"
del ".\GameData\Teams\STCC\Volvo_C30\Volvo Original Racing\00002_Volvo_Original.car"
del ".\GameData\Teams\STCC\Volvo_S60\Team1\S60.car"

del ".\GameData\Teams\CamaroCup\Chevrolet_Camaro\Bryntesson\00006_Bryntesson.car"
del ".\GameData\Teams\CamaroCup\Chevrolet_Camaro\Bryntesson\00066_Bryntesson.car"
del ".\GameData\Teams\CamaroCup\Chevrolet_Camaro\Bryntesson\00069_Bryntesson.car"
del ".\GameData\Teams\CamaroCup\Chevrolet_Camaro\JN-Motorsport\00033_JN-Motorsport.car"
del ".\GameData\Teams\CamaroCup\Chevrolet_Camaro\Lindum-Kongsrud\00037_Lindum-Kongsrud.car"
del ".\GameData\Teams\CamaroCup\Chevrolet_Camaro\Lundstrom\00057_Lundstrom.car"
del ".\GameData\Teams\CamaroCup\Chevrolet_Camaro\Rattviks Racing\00045_Rattviks_Racing.car"
del ".\GameData\Teams\CamaroCup\Chevrolet_Camaro\Team 76\00076_Team_76.car"
del ".\GameData\Teams\CamaroCup\Chevrolet_Camaro\TeamX3M\00052_TeamX3M.car"
del ".\GameData\Teams\CamaroCup\Chevrolet_Camaro\TeamX3M\00077_TeamX3M.car"
